2020-08-24 10:53:43.718906
Auth happening...
Getting songs
Creating dataframe...
Rows:  16
Saved!

Pushed to github.

2020-08-24 10:54:01.334407
Auth happening...
Getting songs
Creating dataframe...
Rows:  16
Saved!

Cmd('git') failed due to: exit code(128)
  cmdline: git push --porcelain origin
  stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
Some error occured while pushing the code

